name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Cambia a la rama que uses para desplegar

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión que prefieras

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: 'Deploy to Azure Static Web Apps'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Auto creado por GitHub
          action: "upload"
          app_location: "/"        # Ruta a tu app (donde está package.json)
          api_location: ""         # Si no tienes backend, deja vacío
          output_location: "dist"  # Carpeta donde Vite genera el build
